using System.Collections.Generic;

namespace ScheduleBoost.Data
{
    public static class ScheduleBoostItemData
    {
        public static readonly Dictionary<string, List<string>> ItemCategories = new()
        {
            {
                "Hardware Store", new List<string>
                {
                    "baggie",
                    "bed",
                    "coffeetable",
                    "displaycabinet",
                    "electrictrimmers",
                    "extralonglifesoil",
                    "fertilizer",
                    "floorlamp",
                    "growtent",
                    "jar",
                    "largestoragerack",
                    "longlifesoil",
                    "mediumstoragerack",
                    "metalsquaretable",
                    "mixingstation",
                    "packagingstation",
                    "packagingstationmk2",
                    "pgr",
                    "trimmers",
                    "potsprinkler",
                    "smallstoragerack",
                    "soil",
                    "soilpourer",
                    "speedgrow",
                    "trashbag",
                    "trashcan",
                    "tv",
                    "wateringcan",

                }
            },
            {
                "Albert Hoover", new List<string>
                {
                    "greencrack",
                    "ogkush",
                    "granddaddypurple",
                    "sourdiesel",
                    "ogkushseed",
                    "greencrackseed",
                    "granddaddypurpleseed",
                    "sourdieselseed"
                }
            },
            {
                "Salvador Moreno", new List<string>
                {
                    "cocaine",
                }
            },
             {
                "Shirley Watts", new List<string>
                {
                    "lowqualitypseudo",
                    "pseudo",
                    "highqualitypseudo",
                    "meth"
                }
            },
            {
                "Gas-Mart", new List<string>
                {
                    "addy",
                    "baggie",
                    "banana",
                    "battery",
                    "bed",
                    "chili",
                    "cuke",
                    "donut",
                    "energydrink",
                    "flumedicine",
                    "gasoline",
                    "horsesemen",
                    "iodine",
                    "jar",
                    "megabean",
                    "motoroil",
                    "mouthwash",
                    "paracetamol",
                    "trashbag",
                    "viagra",
                }
            },
            {
                "Oscar's Store", new List<string>
                {
                    "acid",
                    "airpot",
                    "baggie",
                    "bed",
                    "brickpress",
                    "cauldron",
                    "chemistrystation",
                    "dryingrack",
                    "extralonglifesoil",
                    "fullspectrumgrowlight",
                    "glasoline",
                    "halogengrowlight",
                    "jar",
                    "laboven",
                    "ledgrowlight",
                    "longlifesoil",
                    "mixingstation",
                    "mixingstationmk2",
                    "moisturepreservingpot",
                    "packagingstation",
                    "packagingstationmk2",
                    "phosphorus",
                    "plasticpot",
                    "potsprinkler",
                    "soil",
                    "soilpourer",
                    "suspensionrack",
                }
            },
            {
                 "Bleuballs Boutique", new List<string>
                {
                    "woodensign",
                    "metalsign",
                    "wallmountedshelf",
                    "safe",
                    "antiquewalllamp",
                    "modernwalllamp",
                    "grandfatherclock",
                    "silverwatch",
                    "goldwatch",
                    "silverchain",
                    "goldchain",
                    "goldbar",
                    "artworkbeachday",
                    "artworkmenace",
                    "artworklines",
                    "artworkoffer",
                    "artworkrapscallion",
                    "artworkmillie",
                    "brutdugloop",
                    "chateaulapeepee",
                    "olmanjimmys",
                }
             },
            {               
                "Gun", new List<string>
                {
                    "revolver",
                    "revolvercylinder",
                    "m1911",
                    "m1911mag",
                } 
            }
        };
    }
}
